name: can-build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: library + examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Build
        run: just build
