name: unit-tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Run unit tests
        run: just test-unit
